### ISSUE TITLE
share ~/condor/condor.sh file/functionality (and the plan for bosco/glite/bin/blah_common_submit_functions.sh))

### ISSUE THREAD

**Issue by bdklahn** [copasi/cloud-copasi#24]
In the "pushed incomplete cloud-copasi Dockerfile (and Python requirements.txt) to GitHub" e-mail thread, @hasanbaig mentioned the `condor.sh` file. I don't see that in this repo, nor the stock condor source install. So can/should we include that under `~/condor_overlay`, for `COPY`ing into our Docker container? I guess that's one we created?

Also, I don't see any file names with `blah` in them, at all, anywhere under the stock source install directory. I completely agree with @pmendes that we should not even plan on maintaining a patch for that, and rather depend on their released fix (but we could also put that in the `condor_overlay` directory, only temporarily, for now).
But I wonder . . . since I don't even see any file like that in a recent (e.g. March 1, 2022) source package snapshot; do we even have to deal with that any more? Have they released the "fix" (made it moot) in the source tar.gz files already?

**Comment by hasanbaig** [comment]
Since the `condor` directory is not a part of git repo, this is why you don't see it. It comes with condor installation. So when condor is installed under `condor/` directory, `condor.sh` will be there. 

For condor v9.1.2, **"blah_common_submit_functions.sh"** file is available under `condor/usr/libexec/blahp/` directory. Please check the same directory for the version you are using.

**Comment by hasanbaig** [comment]
and just a reminder again. This is not the location `condor/usr/libexec/blahp/` where we patch the file "blah_common_submit_functions.sh". 

When we add a pool using `bosco_cluster --add <user@remote-machine-address>` command, the `bosco_cluster` script downloads "bosco" on a remote machine and store the **blah_common_submit_functions.sh** file under `bosco/glite/bin/` directory. After the pool is added on a remote machine, we go there and manually patch blah_common_submit_functions.sh file (in fact we just replace it with the correct patched file). 

Now, if we want to add this patch (temporary fix), I have the following suggestion in mind:

- After the pool is added, we can include a command in docker to execute a separate script which will copy the "patched" file (we can keep it in docker) into a remote location `bosco/glite/bin/`. 

I have no idea of what could be the other way to fix this issue. 

@pmendes: May be we can see **"blah_common_submit_functions.sh"** file in the latest version to check if they have fixed that issue (the else statement). Since you have the patch, you know the exact lines where to look at? If it is fixed, we don't need to bother about any hacking stuff.

**Comment by bdklahn** [comment]
Remember, I'm downloading the condor installer source package, and unpacking it into a condor directory. I know we aren't tracking your personal version of the condor directory in GitHub (and we wouldn't want do it that way, anyway).
I get the latest builds from [here](https://research.cs.wisc.edu/htcondor/tarball/current).

I'm saying they no longer have any `blah_common_submit_functions.sh`-like file in their current code. There's not even a `usr/libexec`. There's a `libexec` in the root of the archive, but the directory under is empty. Get one for yourself, unpack it, and do a `find . -name "*blah*"` inside, and see for yourself.

If you are saying there is a separate place (aside from these condor source files), where the remote downloads "bosco", that sounds like bosco is actually separate from the main condor files, and not integrated.
Unless that file (and it's name) is dynamically generated by `bosco_cluster`, or something?
Maybe I am pulling sources which are way too new, and maybe incomplete. I can get v9.8.0. But the main site shows the newest "Feature" release to be v9.5.0.
But it seems a recent build of 9.8.0 would be the most likely place to find that bug fix that you were waiting for.
And maybe the 'fix' means there is no longer a "bosco" with a "blah_common_submit_functions.sh" to deal with, anymore.

**Comment by pmendes** [comment]
I suggest that we stick to the version that we have right now. There are Condor releases every two weeks or so and if they made radical changes, then that will affect our code and break it all over again. Let's get this running with a fixed version. Then we can investigate what's up with the more recent versions.

As Hasan indicated, the patches have to go in the actual user directory in the cluster submit node, and we have to do it on each and every user... (thus why it would be best to have this fixed by Condor)

**Comment by hasanbaig** [comment]
Hi Brian,

This looks really strange.  

I followed the link you shared and tried to download 9.8.0 **stripped** versions (released on March 04 2022) for [CentOS](https://research.cs.wisc.edu/htcondor/tarball/9.1/9.8.0/daily/condor-9.8.0-20220304-x86_64_CentOS7-stripped.tar.gz) as well as for [Ubuntu18 ](https://research.cs.wisc.edu/htcondor/tarball/9.1/9.8.0/daily/condor-9.8.0-20220304-x86_64_Ubuntu18-stripped.tar.gz), and they both contain the directory `/usr/libexec/blahp/`. 

However, the file structure of mac distribution appears to be different.

**Comment by bdklahn** [comment]
I guess I'm not positive what @pmendes means by "the version that we have right now". I'm dynamically pulling whatever version we want to use, when the Docker container is built.
@hasanbaig put in that e-mail that he's using "v9.1.2". [That package](https://research.cs.wisc.edu/htcondor/tarball/9.1/9.1.2/release) was  "Last Modified" on  "2021-07-29 12:54".  I'm not sure how we expect a bug fix to show up in that version.
Version 9.09 is listed as a LTS ("Long Term Support", I assume.) release. [That package](https://research.cs.wisc.edu/htcondor/tarball/9.0/9.0.9/release/) looks to have been "Last Modified" on "2022-01-12 19:34". Isn't that where we would expect to find a bug fix backported to, if we want to stay near our current version? In fact, we might even suspect the fix to show up in the even more recently updated [9.0.12 stable](https://research.cs.wisc.edu/htcondor/tarball/stable/9.0.12/daily/)

It does, indeed, seem that "blah_common_submit_functions.sh" is intended to no longer exist in v9.5.0 "Feature", onward, as the release notes explicitly state "The blahp is no longer separate, it is now an integral part of HTCondor" (and that file no longer exists in the 9.5.0 release tarball).

I just want to know what (temporary) code changes to include in the "condor_overlay" directory. That will include any modifications we make to the stock condor package, after it is downloaded and extracted. Currently it has . . .
- Ed's custom version of bosco_cluster
- the "local" directory additions @hasanbaig was told to create via personal communication
- The condor license, README, and my own README_OVERLAY.md

So do folks want to inspect the 9.0.9 or 9.0.12 tarballs and see if the bug fix is in there (or tell/remind me what exactly that is again or share the code changes or . . .). It sounds like we want to use "stable" 9.0.12 (for now).

And, maybe more importantly: Where does condor.sh exist? If it is something we create, and add to the condor directory, go ahead and add it to condor_overlay, and push it.

**Comment by bdklahn** [comment]
> Hi Brian,
> 
> This looks really strange.
> 
> I followed the link you shared and tried to download 9.8.0 **stripped** versions (released on March 04 2022) for [CentOS](https://research.cs.wisc.edu/htcondor/tarball/9.1/9.8.0/daily/condor-9.8.0-20220304-x86_64_CentOS7-stripped.tar.gz) as well as for [Ubuntu18 ](https://research.cs.wisc.edu/htcondor/tarball/9.1/9.8.0/daily/condor-9.8.0-20220304-x86_64_Ubuntu18-stripped.tar.gz), and they both contain the directory `/usr/libexec/blahp/`.
> 
> However, the file structure of mac distribution appears to be different.

The Docker base image for that Python Django example is based on Ubuntu20, so I thought I should use the package for that.

Interesting . . .

```bash
> find condor-9.8.0-0.576895-x86_64_Ubuntu20-stripped/ -name blah_common_submit_functions.sh
> find condor-9.8.0-0.576894-x86_64_Ubuntu18-stripped/ -name blah_common_submit_functions.sh
condor-9.8.0-0.576894-x86_64_Ubuntu18-stripped/usr/libexec/blahp/blah_common_submit_functions.sh
```

I.e., it is missing from the Ubuntu20 one.

I guess I should compare Ubuntu18 vs 20 for Condor v9.0.12, now.

**Comment by hasanbaig** [comment]
I cannot download and check the directory for ubuntu20 right now but I assume it would also contain the same directory structure. Please use the “stripped” version as we have also used the stripped version on the web server. 



> I guess I'm not positive what @pmendes means by "the version that we have right now". I'm dynamically pulling whatever version we want to use, when the Docker container is built. @hasanbaig put in that e-mail that he's using "v9.1.2". [That package](https://research.cs.wisc.edu/htcondor/tarball/9.1/9.1.2/release) was "Last Modified" on "2021-07-29 12:54". I'm not sure how we expect a bug fix to show up in that version. Version 9.09 is listed as a LTS ("Long Term Support", I assume.) release. [That package](https://research.cs.wisc.edu/htcondor/tarball/9.0/9.0.9/release/) looks to have been "Last Modified" on "2022-01-12 19:34". Isn't that where we would expect to find a bug fix backported to, if we want to stay near our current version? In fact, we might even suspect the fix to show up in the even more recently updated [9.0.12 stable](https://research.cs.wisc.edu/htcondor/tarball/stable/9.0.12/daily/)
> 
> It does, indeed, seem that "blah_common_submit_functions.sh" is intended to no longer exist in v9.5.0 "Feature", onward, as the release notes explicitly state "The blahp is no longer separate, it is now an integral part of HTCondor" (and that file no longer exists in the 9.5.0 release tarball).
> 
> I just want to know what (temporary) code changes to include in the "condor_overlay" directory. That will include any modifications we make to the stock condor package, after it is downloaded and extracted. Currently it has . . .
> 
> * Ed's custom version of bosco_cluster
> * the "local" directory additions @hasanbaig was told to create via personal communication
> * The condor license, README, and my own README_OVERLAY.md
> 
> So do folks want to inspect the 9.0.9 or 9.0.12 tarballs and see if the bug fix is in there (or tell/remind me what exactly that is again or share the code changes or . . .). It sounds like we want to use "stable" 9.0.12 (for now).
> 
> And, maybe more importantly: Where does condor.sh exist? If it is something we create, and add to the condor directory, go ahead and add it to condor_overlay, and push it.

I think what @pmendes meant is if the directory structure is different (as you mentioned you couldn’t find the /usr/libexec/blahp/ in source), then we better proceed with the current version (v9.1.2) which we are using. But yes, if we use v9.1.2 (even temporarily) we have to write a script to replace the patched blah_common_submit_functions.sh file on a remote submit node. 

If we proceed with the latest v9.8.0, we first have to check if the blahp problem is fixed in it or not.

**Comment by bdklahn** [comment]
Ok . . . They are in both, for 9.0.12 . . .
```bash
> find condor-9.0.12-0.576515-x86_64_Ubuntu18-stripped/ -name blah_common_submit_functions.sh
condor-9.0.12-0.576515-x86_64_Ubuntu18-stripped/usr/libexec/blahp/blah_common_submit_functions.sh
condor-9.0.12-0.576515-x86_64_Ubuntu18-stripped/usr/lib/condor/libexec/glite/bin/blah_common_submit_functions.sh
> find condor-9.0.12-0.576516-x86_64_Ubuntu20-stripped/ -name blah_common_submit_functions.sh
condor-9.0.12-0.576516-x86_64_Ubuntu20-stripped/usr/libexec/blahp/blah_common_submit_functions.sh
condor-9.0.12-0.576516-x86_64_Ubuntu20-stripped/usr/lib/condor/libexec/glite/bin/blah_common_submit_functions.sh
```

and . . . "Last Modified" "2022-03-01 19:50".

So I would say the 9.0.12 package is more likely to have bug fixes backported to it than 9.1.2.
9.1.2 appears to be a transient "feature adding" version, while 9.0.12 appears to be in an LTS release line (where bug fixes can show up).

Yes, that makes sense what @pmendes must be saying, that maybe I shouldn't be pulling less stable code from the daily snapshot of a 'current' branch (e.g. 9.8.0, right now).
But I think it will be ok (good, even) to pull from a daily snapshot of a 'stable'  LTS branch.

**Comment by bdklahn** [comment]
Probably 9.5.4 (on their mainpage "Feature" branch) would be the one to go with, if we want to see if the "Feature" makes that issue moot, or whatever.
But, yeah, I guess we'd need to figure out if the/a newer interface on that, or 9.8.0., breaks our code.

So you and Pedro have been monitoring their repo, and haven't seen that fix show up?

**Comment by bdklahn** [comment]
I'm just curious . . . Do you see the fix in this file, on master?
https://github.com/htcondor/htcondor/blob/master/src/blahp/src/scripts/blah_common_submit_functions.sh
Looking at a git blame on that file (in master) above . . . it looks like it is just from bringing in the blahp code base. But I wonder if they just did that to have that file available for reference to make sure their re-implementing the functionality elsewhere. 

It's interesting . . . even when I `git checkout V9_0-branch` (9.0.9 is the LTS version), that file seems to be missing from the code.
So I still wonder if we don't even have to worry about patching that file, anymore.

Ah . . . it is (was) a separate repo.
https://github.com/htcondor/BLAH/tree/devel/src/scripts

**Comment by pmendes** [comment]
Brian, the file you pointed to has the bug fixed. The fix is in lines 619-621 (a missing ELSE). So we should use this version.

Regarding the installation, this is what we were told by one of their developers:

"Can you try the installation instructions in the manual for a single-user setup:
https://htcondor.readthedocs.io/en/latest/getting-htcondor/install-linux-as-user.html

Ignore bosco_install and follow just the instructions in the manual. You can rename the extracted tarball to ~/bosco or any other directory. Once the installation is done, run bosco_cluster --add … to update the binaries on the Slurm submit node."

**Comment by hasanbaig** [comment]
To add to Pedro's message: before running bosco_cluster --add ... command, we have to replace the original bosco_cluster file with our customized version.

**Comment by bdklahn** [comment]
Yep. Those are the instructions I've been using the whole time. The second (Download) paragraph shows where to get the install code from "[our website](https://research.cs.wisc.edu/htcondor/tarball/current/)". We just need to choose a snapshot which actually has the fix in it.
I mean . . . I can look at the code in their convenience installer script, https://get.htcondor.org, to see which version it thinks is best Linux64 stripped one for us. We can try that (trial and error). I guess if no one, even the HTCondor developers, knows which, if any, snapshot the/a fix made it into, we just try the default. But I wasn't planning to have the Docker build try to deal with an interactive user helper shell script for every build. We should be able to figure out which of these versions is the best to use (for now).

Looking at that script . . . It looks like, if you want "stable", it will use: `CHANNEL_DIR=9.0`.
So that seems to mean to use the the 9.0 LTS branch, like I've been thinking (which might very well have the fix, where the v9.1..2 package might never be meant to get the fix).
e.g. `TARBALL_DIR_URL="${TARBALL_BASE_URL}/${CHANNEL_DIR}/current"`
https://research.cs.wisc.edu/htcondor/tarball/9.0/current/

**Comment by bdklahn** [comment]
> To add to Pedro's message: before running bosco_cluster --add ... command, we have to replace the original bosco_cluster file with our customized version.

That's right, @hasanbaig. After the tarball is extracted into `condor`, our `bosco_cluster` from `condor_overlay/bin` will be copied over the one in `condor/bin`

**Comment by bdklahn** [comment]
Ok. I think I'll choose 9.0.12, for the download.
Then do the  . . .
```bash
cd condor
./bin/make-personal-from-tarball
```
. . . and see if condor.sh is there, or appears after the above command..

**Comment by bdklahn** [comment]
Ok. I pulled the [9.0](https://research.cs.wisc.edu/htcondor/tarball/9.0/current/) [tarball](https://research.cs.wisc.edu/htcondor/tarball/9.0/current/condor-x86_64_Ubuntu20-stripped.tar.gz) (which seems to be what that convenience script would give you), which gives me `condor-9.0.9-1.1-x86_64_Ubuntu20-stripped` . . .
The file is there, and . . . 
```bash
    616           if [ ! -z $xfile  ] ; then
    617               if [ ! -z "$bls_opt_outputflstringremap" ] ; then
    618                   read xfileremap <&6
    619               else
    620                   xfileremap=""
    621               fi
```
Does that seem right/fixed, @hasanbaig and @pmendes ?

**Comment by pmendes** [comment]
@bdklahn yes, this is correct (ie bug is fixed there)

**Comment by hasanbaig** [comment]
I am not sure if this is the right "else" which was missing previously. 
@pmendes We need to check this carefully. I just check the file `/home/cloudcopasi/condor/usr/libexec/blahp/blah_common_submit_functions.sh` on the webserver, and it also contains this "else" structure. I was hoping that this should not be there because we still add the patch manually after adding every user on the remote host. 

Kindly confirm if this is the right "else" structure which was earlier missing.

**Comment by bdklahn** [comment]
If this helps, here is what it looks like in the `condor-9.1.2-1.1-x86_64_Ubuntu20-stripped` snapshot (updated Jul 29 2021 vs. Jan 12 2022 for `condor-9.0.9-1.1-x86_64_Ubuntu20-stripped`)

```bash
    616 
    617               if [ -z $xfileremap ] ; then
    618                 xfileremap="$xfile"
    619               fi
    620               if [ "${xfileremap:0:1}" != "/" ] ; then
    621                 xfileremap=${bls_opt_workdir}/${xfileremap}
```

**Comment by hasanbaig** [comment]
> If this helps, here is what it looks like in the `condor-9.1.2-1.1-x86_64_Ubuntu20-stripped` snapshot (updated Jul 29 2021)
> 
> ```shell
>     616 
>     617               if [ -z $xfileremap ] ; then
>     618                 xfileremap="$xfile"
>     619               fi
>     620               if [ "${xfileremap:0:1}" != "/" ] ; then
>     621                 xfileremap=${bls_opt_workdir}/${xfileremap}
> ```

Yes, there is a series of if-else structure. Here else structure is missing and this is what we need to make sure if this is the one causing the error or what @pmendes mentioned in his comment:  

> Brian, the file you pointed to has the bug fixed. The fix is in lines 619-621 (a missing ELSE). So we should use this version.

**Comment by hasanbaig** [comment]
I have verified. Pedro is right! This is the fixed bug!

**Comment by hasanbaig** [comment]
I think we might have fixed this bug ourselves on the cloud-copasi web server. But then whenever a pool is added, we have to fix the bug manually on remote submit node because the files are not copied from the CC web server there, rather directly downloaded from HTCondor website. 

I hope we won't need to do that again after this bug is being fixed.

**Comment by bdklahn** [comment]
Awesome!
So it looks like https://research.cs.wisc.edu/htcondor/tarball/9.0/current/condor-x86_64_Ubuntu20-stripped.tar.gz, is what we want (which apparently their installer script would consider "stable").
That might, over time, continue to get critical bug fixes. But I might not expect it ever get changes which would break our interface. And if it does, we can always try to find the "hardlink" url to that tar file, to pin to.

**Comment by bdklahn** [comment]
> I think we might have fixed this bug ourselves on the cloud-copasi web server. But then whenever a pool is added, we have to fix the bug manually on remote submit node because the files are not copied from the CC web server there, rather directly downloaded from HTCondor website.
> 
> I hope we won't need to do that again after this bug is being fixed.

Yes. I would _hope_ their code that downloads things on the submit node would also refer to that fixed snapshot. It seems logical that it would go to https://research.cs.wisc.edu/htcondor/tarball/9.0/current/ to get the code (like the downloader script does). All of the assets there seem to have been updated on '2022-01-12' (except CenOS8, on 2021-12-02).
So we can just test and see. But it seems hopeful.

**Comment by pmendes** [comment]
I think this will solve the problem, and we won't have to fix anything after this. We could have done things differently but I thought it would be a temporary kludge and would confuse us down the line. It was better to wait for the bug to be fixed and everything would work with our code as it should (after all the bug was upstream, not on our code).

Hopefully we may be able to close this issue

**Comment by bdklahn** [comment]
Ok.
I changed the Docker file to use that snapshot, and run the personal install, etc.
The build seemed to work right, putting our bosco_cluster in, etc., etc., and condor/condor.sh appeared.
`. condor/condor.sh` (and `condor_master`, even) ran without error.
I think I'll plan on having this build with GitHub Actions, soon, to make it easier for others to test interactively, while we fill out this install.

**Comment by bdklahn** [comment]
Looks like this one is resolved.
