### ISSUE TITLE
bosco_cluster issues

### ISSUE THREAD

**Issue by pmendes** [copasi/cloud-copasi#30]
we have bosco_cluster as a copy to replace the original bosco_cluster from HTCondor. However copying over is not a good solution for when there are new versions of HTCondor. Instead the best way to do this is to actually patch the original bosco_cluster (*) with the changes needed. This requires making a patch file, which I will do and add to the changes later on.

(*) the second issue is that bosco_cluster in HTCondor has been renamed to condor_remote_cluster (they still have bosco_cluster as a symlink, but I expect that will go away in future versions...)

So, to resolve the two issues in one: I will create a patch file for condor_remote_cluster and then rewrite the instructions to have the patch applied rather than copying a file over.

**Comment by hasanbaig** [comment]
if the file name 'bosco_cluster' is changed to 'condor_remote_cluster', we will also need to update the code to execute correct condor commands.

**Comment by bdklahn** [comment]
Yes . . . I always thought this was . . . not a good way (have our own version of that file, we need to try and keep up to date).

I did note the copasi-specific additions in there, but I didn't read the whole file super closely (comparing it to the stock one). But I wonder if we also could just have a wrapper script that sets some variables, etc., then calls or sources that stock bosco_cluster file.

But maybe some of the original modifications are more "entangled" than just setting up or overriding some variables, etc.

**Comment by pmendes** [comment]
@hasanbaig they have changed the name of the file, but they still provide a symlink with the same name. So it still works. If they remove the symlink we can either change the code to call the appropriate file, or create a symlink ourselves. For now we don't need to do anything about the name. bosco_cluster still works

(I do notice that this file has changed name a few times, as it originally was called bosco_add and then was renamed to bosco_cluster and now it is condor_remote_cluster)

**Comment by pmendes** [comment]
A major problem of creating a good patch file is that our version of bsco_cluster has been changed in ways that make it not similar to any version of the original. The current file seems to say it was edited form version 9.1.2, but it clearly was not. It has too many sections of code that are different from that version. It seems to be some hybrid made from an earlier version but with a few changes added. So this may even be a problem because it does not do everything that v9.1.2 should do. This strengthens the argument that we really need to use a patch, so that when condor is upgraded this file stays in sync with the rest of condor. (Their renaming of the file does not help either...)

**Comment by hasanbaig** [comment]
@pmendes: After upgrading to v9.1.2 I tried to use the same customized `bosco_cluster` file which was a part of the original repository (condor v8.8.13). It did not work because the v9.1.2 determines the remote OS (CentOS) and directly install the corresponding condor version on a remote machine. I then used the `bosco_cluster` (**v9.1.2**) and reflected the modifications of old file (v8.8.13) in the new one (v9.1.2). I also had to make slight modifications in  cloud-copasi code to make it work with `bosco_cluster` file v9.1.2

So, you are right that you see sections in current version v9.1.2 which are not present in the original one. Those sections are extracted from v8.8.13.

**Comment by pmendes** [comment]
@hasanbaig thanks for clarifying. I think I managed to isolate the changes that are needed by us in a patch file. I've tested it and it works cleanly on the bosco_cluster from v.9.2.1 . Now I need to see if it works on the new version. If the patch works there too, I then need to see if the patched file works correctly. This is taking time but it will be a much better solution.

**Comment by pmendes** [comment]
OK, the patch also works cleanly on the new condor_remote_cluster, so I  added the patch file to the repository. But let's not yet delete bosco_cluster from the repository as I first need to confirm the patched files work well.

**Comment by bdklahn** [comment]
I'm trying to recall if I ever knew the exact reasons Ed felt he needed to modify that in the first place.
I wonder if (now?) there is a "correct" way to customize/override such settings, via env variables or another config file.
Because running a patch also seems a little "heavy". It sound like Pedro already basically figured out all our customization to that. But I was thinking it would could be informative to look at a diff of the original stock one, vs ours, to get clear idea of what Ed was trying to accomplish. And the reasoning might even be stated in (an) early commit message(s).

Anyway, I guess I might deduce from Pedro's patch.

And I will want to delete that COPY line from the Docker file, now.

But, yes, a patch is better than the "full maintain and clobber". :-)

**Comment by hasanbaig** [comment]
> OK, the patch also works cleanly on the new condor_remote_cluster, so I added the patch file to the repository. But let's not yet delete bosco_cluster from the repository as I first need to confirm the patched files work well.

Awesome! 👍

**Comment by pmendes** [comment]
@bdklahn I know well why it is modified; it tests the cluster by sending a copasi file and waiting for its valid return. I think this is good and there is no good other way of doing this. The changes are actually minimal.

A word of caution, though: this has not yet been tested. I will have to finish installing cloud-copasi before we can decide if the patch is correct or not. There were a lot of other differences between the original file and ours (several diff chunks) which I cannot explain why they were needed by us. They genuinely looked like differences in the underlying code being from different versions. I removed all those chunks but maybe something in there could be important. I will wait until confirming all is ok until I close this issue.

**Comment by pmendes** [comment]
So I've now tested this patch file against the older bosco_cluster and the new condor_remote_cluster and it works on both. The patched bosco_cluster from condor 9.1.2 (the same version that Hasan is running on cloud-copasi-new) is operational. 

This means that we should now use the patch file rather than copying our Frankenstein modified version over. At some point we should remove the modified version from the repository.

I am closing this one.
